id: A46619A77
title: Ārya Mañjuśrī Tantra Garbha
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:27:23.644844
  last_modified_at: 2022-02-28 23:27:23.644847
