id: A46619A77
title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected Words
  of the Buddha
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:27:23.642053
  last_modified_at: 2022-02-28 23:27:23.642056
