id: A46619A77
title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of the
  Guru (Lama Sangdü)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:27:23.637956
  last_modified_at: 2022-02-28 23:27:23.637963
