id: A46619A77
title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching from
  the Lama Sangdü'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:27:23.623458
  last_modified_at: 2022-02-28 23:27:23.623465
